package unsw.dungeon.model.entities;

public enum EntityType {
	UNLITBOMB, LITBOMB, DOOR, EXIT, KEY, INVINCIBLEPOTION, INVISIBLEPOTION, SWITCH, SWORD, TREASURE, WALL, BOULDER,
	ENEMY, PLAYER, WIZARD, PRINCESS;
}
